### PR TITLE
Add Keimyung University

### PR DESCRIPTION
**Pull request by Xwilarg**
Hey,
We had a hard time the first time we had to set our password at Keimyung University, so I thought this would be a good place to post that.

### CODE REVIEW

**Comment by duffn** [comment]
Thanks for the PR.

Can you distinguish between the 2nd and 3rd screenshots? What are the messages?

**Comment by Xwilarg** [comment]
> Thanks for the PR.
> 
> Can you distinguish between the 2nd and 3rd screenshots? What are the messages?

One is telling you that you can't have more than 3 times the same characters and the other that you can't have more than 2 consecutive numbers in a row.

**Comment by Xwilarg** [comment]
Any news?
If you need more information and if you need me to change something, don't hesitate to ask.

**Comment by duffn** [comment]
Thank you for the contribution!

**Pull request merged**
