### PR TITLE
 Add CIBC (Canadian Imperial Bank of Commerce) 

### PR DESCRIPTION
**Pull request by Candunc**

### CODE REVIEW

**Comment by duffn** [comment]
Can you show a screenshot with the 12 character max error message?

**Comment by Candunc** [comment]
I'm afraid it doesn't prompt an error, the field in both the web version and the app just doesn't take input beyond 12 characters.

**Comment by duffn** [comment]
Okay. Thanks for the submission.

**Comment by mattschlosser** [comment]
Changes to this seem to have been overwritten. I no longer see this site on the main page. I was going to add it but already saw a screenshot for it in the screenshots folder.

**Pull request merged**
