### PR TITLE
Added Myswisslife

### PR DESCRIPTION
**Pull request by adrienthiery**
This is pretty scary because they manage social/health insurance data and also life insurance.

### CODE REVIEW

**Comment by adrienthiery** [comment]
Finally got around to fix that 😅

**Comment by adrienthiery** [comment]
I'm not sure how `.rst` works, so I couldn't visualise the images... Do I need to do anything else ?

**Comment by adrienthiery** [comment]
Also, @duffn , if you need help maintaining, I'd love to help :)

**Comment by duffn** [comment]
Thank you!

**Pull request merged**
