### PR TITLE
Add Chegg

### PR DESCRIPTION
**Pull request by adambowles**

### CODE REVIEW

**Comment by duffn** [comment]
In the last image, the email is empty and it just shows "email and password does not match". Can you show it indicating that you can't login with either the new or old password?

**Comment by adambowles** [comment]
I blanked out the email for my privacy, I can put some other obvious obscuring method if you’d like?

**Comment by adambowles** [comment]
Also, I don't know how I'd obviously indicate trying 2 different passwords

**Comment by duffn** [comment]
I think your description is fine, if maybe you could obscure the email like in the 2nd picture here, that would make it clear that there's an email in there. https://github.com/dumb-password-rules/dumb-password-rules#best-buy

**Comment by adambowles** [comment]
@duffn Done

**Comment by duffn** [comment]
Thanks for the PR!

**Pull request merged**
