### PR TITLE
alibaba intelligence detected

### PR DESCRIPTION
**Pull request by tangoabcdelta**
> Include the name of the site with a link.

name of the site: **[alibaba.com](https://www.alibaba.com/)**
link for the password reset site: **[link](https://passport.alibaba.com/ac/password_modify.htm?fromSite=4&lang=en_US)**

> Add a clean comment about the dumb password rule (optional).

"Your password should consist of at least 2 uppercase letters, 2 lowercase letters, 2 numbers and 2 punctuation marks" / "请输入新的登录密码"

> Include at least one screenshot.

**_Included_**

> Keep the sites in alphabetical order.

Not applicable

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
You are missing parts for a complete PR.

**Comment by tangoabcdelta** [comment]
Updated the comment with the required information

**Comment by duffn** [comment]
Can you delete the extra screenshot please?

**Comment by tangoabcdelta** [comment]
Yes @duffn, deleted + cleared the clutter.
Thank you.

**Review by duffn — APPROVED** [review]

**Comment by duffn** [comment]
Thank you for the contribution!

**Pull request merged**
