### PR TITLE
Add ups.com

### PR DESCRIPTION
**Pull request by Yannickvdv**

### CODE REVIEW

**Comment by duffn** [comment]
Thanks. I don’t think 7-26 characters is one I’ve seen before.

**Comment by Yannickvdv** [comment]
@duffn I just now noticed there is an extra `+` on [line 1099](https://github.com/dumb-password-rules/dumb-password-rules/pull/243/files#diff-88b99bb28683bd5b7e3a204826ead112R1099). Which breaks the formatting of the table of contents. Do you want me to create a separate PR to fix this?

**Comment by duffn** [comment]
@Yannickvdv Please, that would be great.

**Comment by Yannickvdv** [comment]
@duffn https://github.com/dumb-password-rules/dumb-password-rules/pull/248

**Pull request merged**
