### PR TITLE
add Vancity Credit Union

### PR DESCRIPTION
**Pull request by kalin**
I think this may actually be the worst one on the list.

### CODE REVIEW

**Comment by duffn** [comment]
This is a password that you use to login on the website and do your banking and not something like a PIN that you use at an ATM?

**Comment by kalin** [comment]
Yes, the PAC (for web and mobile banking) is different from a PIN (for use at an ATM).

In fact, here is a helpful video to explaining the difference!

https://support.vancity.com/249-pac-pin/

Maybe I should add that to the description as well?

**Comment by duffn** [comment]
No, this is fine. I just wanted to make sure it was an actual password for the website considering how absolutely ridiculous it is.

**Comment by duffn** [comment]
Thanks for your PR! This is indeed a completely dumb password rule.

**Comment by cpb** [comment]
I wouldn't be surprised if it afflicted many/all credit unions in BC, as there is supposedly some shared platform.

**Pull request merged**
