### PR TITLE
Add USAA

### PR DESCRIPTION
**Pull request by tayloramurphy**
This PR adds USAA as an egregious offender of bad password policy. 

Thank you for this project!

### CODE REVIEW

**Comment by danehrlich1** [comment]
LIterally just came to this repo to put a pull request in for this, damn! But glad other ppl think this too. It's so bad! 12 characters! And they didn't even offer 2FA until like 2016 either...there wasn't even an SMS option......

**Comment by tayloramurphy** [comment]
@danehrlich1 I saw this project and immediately dropped everything I was doing to add USAA! I've tweeted at them and talked to their CS folks and have gotten nowhere. Absolutely ridiculous!

**Comment by duffn** [comment]
Well then, it seems like the USAA password rules are very highly regarded. 😆 

Thanks for the PR.

**Comment by danehrlich1** [comment]
Tweeted at a couple of CS people Apple just now we’ll see what happens

https://twitter.com/danehrlich11/status/1169963507669798912?s=21

**Comment by duffn** [comment]
USAA seems to think that they're okay. https://twitter.com/USAA_help/status/1169988529646002176

**Comment by souldzin** [comment]
> Passwords are one level of security

This is a really disappointing response from them... Secrets are *one level* of security, just like the foundation of a home is *one level* of construction...

Thanks for calling them out on this @tayloramurphy! 🙇

**Pull request merged**
