### PR TITLE
add Chase bank

### PR DESCRIPTION
**Pull request by nainslie**
They have some silly rules about restricted special characters, not allowing more than 2 sequential or repeated characters and a max length restriction.  It scares me to think of what kind of backend technical problems required these restrictions.

### CODE REVIEW

**Comment by scottarver** [comment]
Chase ignores any case on the password, type it in all caps, all lowercase, doesnt matter.

**Comment by duffn** [comment]
> Chase ignores any case on the password, type it in all caps, all lowercase, doesnt matter.

No way, that's terrible. Can you add that to the PR @nainslie if you can confirm?

**Comment by kesslern** [comment]
I've had conversations online with others about this, and at least other one person attempted their password in multiple cases and claimed it only worked in the correct case.

Personally, I'm able to log in to the Android app and the web interface with any case password. If I'm adding a new device, the "confirm password" prompt with the provided code is case sensitive. Others reported that every prompt was case sensitive.

#179 removed Chase from the list claiming Chase uses case insensitive passwords, but I just tested and am still able to login with any case.

**Comment by nainslie** [comment]
The website at least is case sensitive when it comes to passwords.  Just confirmed.

**Comment by duffn** [comment]
Thanks. Can you please resolve the conflicts?

**Comment by nainslie** [comment]
Conflicts are resolved and this PR should be up-to-date with upstream now.

**Comment by duffn** [comment]
Thank you.

**Comment by remram44** [comment]
I also confirm that the chase.com website ignores case and I think this is bad enough to appear in the list.

**Comment by duffn** [comment]
This PR was merged - it is on the list.

**Comment by remram44** [comment]
@duffn The case insensitivity isn't

**Comment by duffn** [comment]
@remram44 I'll happily review PRs.

**Comment by remram44** [comment]
Thanks! I was not trying to be difficult, just wanted to confirm the situation since this was mentioned before and removed (and it was discussed here but not included). I opened #236.

Hopefully someone there notices this incredible list and does something about that!

**Pull request merged**
